server:
  port: 8989
  context-path: /admin
  jsp-servlet:
    init-parameters:
      development: true

http:
  multipart:
    #   单个文件的大小限制
    max-file-size: 10Mb
    #   一次请求的文件限制
    max-request-size: 100Mb

spring:
  activemq:
    broker-url: tcp://49.233.93.39:61616
    user: admin
    password: admin
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://49.233.93.39:3306/backstage
    username: root
    password: taidou.0320
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      suffix: .jsp
      prefix: /


mybatis:
  mapper-locations: classpath:com/yijiayifeng/mapper/*Mapper.xml
  type-aliases-package: com.yijiayifeng.entity